### ISSUE TITLE
o365预训练权重加载问题

### ISSUE THREAD

**Issue by leoxxxxxD** [Atten4Vis/LW-DETR#13]
如果自定义数据集的类别不在o365中，该怎么处理权重加载问题呢

**Comment by xbsu** [comment]
> 如果自定义数据集的类别不在o365中，该怎么处理权重加载问题呢

可以不加载预训练的class embedding权重，将scripts/lwdetr_<model_size>_coco_train.sh中的"--pretrain_keys_modify_to_load"替换为"--pretrain_exclude_keys"
