### ISSUE TITLE
Question about denoising and group detr

### ISSUE THREAD

**Issue by ymzis69** [Atten4Vis/LW-DETR#21]
Thank you for your amazing work. I have a question. In your Group DETR paper, it is noted that the DN-DETR + Group DETR method improves the mAP. Why did you only use the Group DETR training method in LW-DETR but not the DeNoising training method? Have you tried adding the DeNoising method in LW-DETR experiments? Looking forward to your response.

**Comment by xbsu** [comment]
Actually, the DN-DETR + Group DETR method improves mAP when training is done solely on the COCO dataset without pre-training. However, when a pre-training followed by a fine-tuning process is used, the performance gain from the DeNoising training method is minimal. Therefore, to simplify the approach, we only used Group DETR training method.

**Comment by ymzis69** [comment]
Thank you for your reply. I wish you success in your studies and work.
