### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by Richarn290** [Atten4Vis/LW-DETR#26]
自己的数据集中共有9000多张图片，运行的是sh scripts/lwdetr_small_coco_train.sh /path/to/your/COCODIR脚本，训练了40多个epoch map0.5一直维持在0.34没比第一个epoch增加多少，是因为超参数的原因吗（都是默认的，没有修改），请问该怎么调呢

**Comment by SuiFengLai** [comment]
请问超参数怎么调呢？单卡训练的情况
